import type { Idioma } from "@/i18n/config";

/** Textos da página de resultados nos três idiomas. */
export const textos = {
  pt: {
    altHero: "Lavoura demonstrando resultados BIO-X",
    evidencia: "Evidência Aplicada",
    hero1: "O campo não mente.",
    hero2: "Ele mostra.",
    heroApoio: "Deixamos o laboratório e fomos para onde a tecnologia é realmente posta à prova: na sua realidade, lado a lado, safra após safra.",
    veja: "Veja os resultados",
    diferenca1: "A diferença só importa",
    diferenca2: "se for vista lado a lado.",
    comparacao: [["Mesmo ambiente", "A comparação parte de condições equivalentes: mesma propriedade, solo e safra."], ["Aplicação real", "Tecnologia observada dentro do manejo e da rotina operacional que você já faz."], ["Raiz e Produtividade", "O resultado que salta aos olhos quando a planta é arrancada da terra."]],
    diario: "Diário de Campo",
    lentes1: "O que nossas lentes",
    lentes2: "capturaram.",
    diasCampo: "Dias de campo, parcelas comparativas e a transformação real documentada em imagens.",
    registro: "Registro",
    transformacao: "Transformação Visível",
    tecLavoura: "Tecnologia aplicada na lavoura",
    quem1: "Quem vive do campo,",
    quem2: "assina embaixo.",
    anterior: "Ver anterior",
    proximo: "Ver próximo",
    arraste: "Arraste para ver mais",
    fotoDe: "Foto de",
    assista: "Assista ao Caso de Sucesso",
    acao1: "A biotecnologia em",
    acao2: "ação.",
    semVideo: "Seu navegador não suporta a reprodução de vídeos.",
  },
  en: {
    altHero: "Crop field showing BIO-X results",
    evidencia: "Applied Evidence",
    hero1: "The field doesn’t lie.",
    hero2: "It shows.",
    heroApoio: "We left the lab and went where technology is truly put to the test: your reality, side by side, season after season.",
    veja: "See the results",
    diferenca1: "The difference only matters",
    diferenca2: "when you see it side by side.",
    comparacao: [["Same environment", "The comparison starts from equivalent conditions: same farm, soil and season."], ["Real application", "Technology observed within the management and daily operations you already have."], ["Roots and Yield", "The result that jumps out when the plant is pulled from the ground."]],
    diario: "Field Journal",
    lentes1: "What our lenses",
    lentes2: "captured.",
    diasCampo: "Field days, comparison plots and real transformation documented in pictures.",
    registro: "Record",
    transformacao: "Visible Transformation",
    tecLavoura: "Technology applied in the field",
    quem1: "Those who live off the land",
    quem2: "back it up.",
    anterior: "Previous",
    proximo: "Next",
    arraste: "Swipe to see more",
    fotoDe: "Photo of",
    assista: "Watch the Success Story",
    acao1: "Biotechnology in",
    acao2: "action.",
    semVideo: "Your browser does not support video playback.",
  },
  es: {
    altHero: "Cultivo que demuestra resultados BIO-X",
    evidencia: "Evidencia Aplicada",
    hero1: "El campo no miente.",
    hero2: "Lo demuestra.",
    heroApoio: "Dejamos el laboratorio y fuimos adonde la tecnología realmente se pone a prueba: en su realidad, lado a lado, cosecha tras cosecha.",
    veja: "Vea los resultados",
    diferenca1: "La diferencia solo importa",
    diferenca2: "si se ve lado a lado.",
    comparacao: [["Mismo ambiente", "La comparación parte de condiciones equivalentes: misma propiedad, suelo y cosecha."], ["Aplicación real", "Tecnología observada dentro del manejo y la rutina operativa que usted ya realiza."], ["Raíz y Productividad", "El resultado salta a la vista cuando la planta se arranca de la tierra."]],
    diario: "Diario de Campo",
    lentes1: "Lo que nuestras lentes",
    lentes2: "capturaron.",
    diasCampo: "Días de campo, parcelas comparativas y la transformación real documentada en imágenes.",
    registro: "Registro",
    transformacao: "Transformación Visible",
    tecLavoura: "Tecnología aplicada en el cultivo",
    quem1: "Quienes viven del campo",
    quem2: "lo respaldan.",
    anterior: "Ver anterior",
    proximo: "Ver siguiente",
    arraste: "Deslice para ver más",
    fotoDe: "Foto de",
    assista: "Mire el Caso de Éxito",
    acao1: "La biotecnología en",
    acao2: "acción.",
    semVideo: "Su navegador no admite la reproducción de videos.",
  },
} satisfies Record<Idioma, Record<string, unknown>>;
