import type { Idioma } from "@/i18n/config";

/** Textos da janela de contato nos três idiomas. */
export const textosContato = {
  pt: {
    olho: "Fale com a BIO-X",
    titulo: "Conte um pouco sobre você",
    apoio: "Um especialista da BIO-X responde em até um dia útil.",
    fechar: "Fechar",
    nome: "Nome",
    nomeDica: "Seu nome completo",
    email: "E-mail",
    emailDica: "voce@empresa.com.br",
    papel: "Você é",
    dono: "Dono(a) da empresa",
    representante: "Representante da empresa",
    empresa: "Empresa",
    empresaDica: "Nome da empresa que você representa",
    mensagem: "Mensagem",
    opcional: "opcional",
    mensagemDica: "Conte o que você produz, onde e qual desafio quer resolver.",
    enviar: "Enviar",
    enviando: "Enviando…",
    ou: "ou",
    whatsapp: "Falar pelo WhatsApp",
    privacidade: "Usamos seus dados só para responder a este contato.",
    obrigatorio: "Preencha este campo.",
    emailInvalido: "Confira o e-mail.",
    escolhaPapel: "Escolha uma opção.",
    sucessoTitulo: "Recebemos seu contato!",
    sucessoTexto: "Obrigado, {nome}. Nossa equipe vai responder no e-mail {email}.",
    emailAbertoTitulo: "Quase lá!",
    emailAbertoTexto:
      "Abrimos o seu programa de e-mail com a mensagem pronta — é só enviar. Se preferir, fale com a gente pelo WhatsApp.",
    erro: "Não conseguimos enviar agora. Tente de novo ou fale pelo WhatsApp.",
    ok: "Fechar",
    // Mensagem que vai para o WhatsApp / e-mail
    msgOla: "Olá! Vim pelo site da BIO-X.",
    msgNome: "Nome",
    msgEmail: "E-mail",
    msgEmpresa: "Empresa",
    msgPapel: "Sou",
    msgMensagem: "Mensagem",
    assunto: "Contato pelo site",
  },
  en: {
    olho: "Talk to BIO-X",
    titulo: "Tell us a bit about you",
    apoio: "A BIO-X specialist will reply within one business day.",
    fechar: "Close",
    nome: "Name",
    nomeDica: "Your full name",
    email: "Email",
    emailDica: "you@company.com",
    papel: "You are",
    dono: "The company owner",
    representante: "A company representative",
    empresa: "Company",
    empresaDica: "Name of the company you represent",
    mensagem: "Message",
    opcional: "optional",
    mensagemDica: "Tell us what you produce, where, and which challenge you want to solve.",
    enviar: "Send",
    enviando: "Sending…",
    ou: "or",
    whatsapp: "Chat on WhatsApp",
    privacidade: "We only use your details to reply to this message.",
    obrigatorio: "Please fill in this field.",
    emailInvalido: "Please check the email address.",
    escolhaPapel: "Please choose an option.",
    sucessoTitulo: "We got your message!",
    sucessoTexto: "Thank you, {nome}. Our team will reply to {email}.",
    emailAbertoTitulo: "Almost there!",
    emailAbertoTexto:
      "We opened your email app with the message ready — just hit send. If you prefer, reach us on WhatsApp.",
    erro: "We couldn’t send it right now. Please try again or reach us on WhatsApp.",
    ok: "Close",
    msgOla: "Hello! I found BIO-X through the website.",
    msgNome: "Name",
    msgEmail: "Email",
    msgEmpresa: "Company",
    msgPapel: "I am",
    msgMensagem: "Message",
    assunto: "Website contact",
  },
  es: {
    olho: "Hable con BIO-X",
    titulo: "Cuéntenos un poco sobre usted",
    apoio: "Un especialista de BIO-X responde en hasta un día hábil.",
    fechar: "Cerrar",
    nome: "Nombre",
    nomeDica: "Su nombre completo",
    email: "Correo electrónico",
    emailDica: "usted@empresa.com",
    papel: "Usted es",
    dono: "Dueño(a) de la empresa",
    representante: "Representante de la empresa",
    empresa: "Empresa",
    empresaDica: "Nombre de la empresa que representa",
    mensagem: "Mensaje",
    opcional: "opcional",
    mensagemDica: "Cuéntenos qué produce, dónde y qué desafío quiere resolver.",
    enviar: "Enviar",
    enviando: "Enviando…",
    ou: "o",
    whatsapp: "Hablar por WhatsApp",
    privacidade: "Usamos sus datos solo para responder a este contacto.",
    obrigatorio: "Complete este campo.",
    emailInvalido: "Revise el correo electrónico.",
    escolhaPapel: "Elija una opción.",
    sucessoTitulo: "¡Recibimos su contacto!",
    sucessoTexto: "Gracias, {nome}. Nuestro equipo responderá al correo {email}.",
    emailAbertoTitulo: "¡Casi listo!",
    emailAbertoTexto:
      "Abrimos su programa de correo con el mensaje listo: solo tiene que enviarlo. Si prefiere, hable con nosotros por WhatsApp.",
    erro: "No pudimos enviarlo ahora. Inténtelo de nuevo o hable por WhatsApp.",
    ok: "Cerrar",
    msgOla: "¡Hola! Llegué por el sitio de BIO-X.",
    msgNome: "Nombre",
    msgEmail: "Correo",
    msgEmpresa: "Empresa",
    msgPapel: "Soy",
    msgMensagem: "Mensaje",
    assunto: "Contacto desde el sitio",
  },
} satisfies Record<Idioma, Record<string, string>>;
