import type { Idioma } from "@/i18n/config";

/** Textos da página "A BIO-X" nos três idiomas. */
export const textos = {
  pt: {
    altRaizes: "Raízes de plantas com BIO-X Agricultura Única e no padrão da fazenda, lado a lado",
    comBiox: "BIO-X Agricultura Única",
    padraoFazenda: "Padrão fazenda",
    ladoALado: "Lado a lado",
    legendaRaizes: "A mesma cultura, com BIO-X Agricultura Única e no manejo padrão da fazenda.",
    metaTitulo: "A BIO-X",
    metaDescricao: "Mais de 30 anos de experiência transformados em biotecnologia aplicada à agricultura, saneamento e produção animal.",
    etapas: [["Origem", "Microorganismos benéficos selecionados para atuar de forma natural nos processos biológicos."], ["Aplicação", "A tecnologia é aplicada diretamente no ambiente onde a transformação precisa acontecer."], ["Equilíbrio", "Os microorganismos benéficos favorecem uma nova dinâmica biológica no meio."], ["Resultado", "Mais equilíbrio, eficiência e novas possibilidades para cada cadeia produtiva."]],
    olhoHero: "A estrutura por trás da BIO-X",
    hero1: "Biologia que",
    hero2: "atravessa",
    hero3: "gerações.",
    heroApoio: "A BIO-X nasceu da união entre mais de três décadas de experiência no agronegócio e no tratamento de efluentes com uma das tecnologias mais antigas e eficientes da natureza: os microorganismos.",
    historiaBotao: "Conheça nossa história",
    cienciaVida: "Ciência aplicada à vida",
    altDiaCampo: "Estande da BIO-X em uma feira do agronegócio",
    expInovacao: "Experiência que gera inovação",
    conhecCampo: "Conhecimento de campo transformado em tecnologia.",
    historiaCampo: "Uma história construída no campo",
    anos: "+ anos",
    expReunindo: "Experiência reunindo agronegócio, tratamento de efluentes, pesquisa e aplicação prática.",
    nossaOrigem: "Nossa origem",
    antes1: "Antes da tecnologia,",
    antes2: "veio a",
    antes3: "experiência.",
    agro: "Agronegócio",
    agroTexto: "A vivência de décadas no campo construiu o entendimento dos desafios reais enfrentados diariamente pelos produtores.",
    efluentes: "Tratamento de efluentes",
    efluentesTexto: "Três décadas de experiência em processos de tratamento ampliaram o conhecimento sobre equilíbrio biológico.",
    pergunta1: "Dessa combinação surgiu uma pergunta:",
    pergunta2: "e se a própria biologia pudesse resolver problemas que exigem soluções complexas?",
    altCampo: "Experiência no campo",
    altLab: "Tecnologia e laboratório",
    tecBiox: "Tecnologia BIO-X",
    processo1: "Um processo natural.",
    processo2: "Uma transformação em cadeia.",
    processoApoio: "A tecnologia BIO-X atua criando condições favoráveis para que microorganismos benéficos assumam um papel ativo no equilíbrio dos ambientes em que são aplicados.",
    ilustracao: "Ilustração da etapa",
    etapa: "Etapa",
    altTextura: "Textura de fundo",
    principio: "O princípio",
    natureza1: "A natureza fazendo",
    natureza2: "o trabalho pesado.",
    principio1: "Os microorganismos benéficos atuam em conjunto com o ambiente, influenciando populações neutras e reduzindo condições favoráveis a microorganismos indesejados.",
    principio2: "A base da tecnologia utiliza microorganismos como lactobacilos e leveduras, amplamente conhecidos também por aplicações na indústria alimentícia.",
    emNumeros: "BIO-X em números",
    medida1: "Experiência que",
    medida2: "pode ser medida.",
    altResultados: "Resultados em campo",
    sustenta: "O que sustenta a BIO-X",
    principios1: "Três princípios.",
    principios2: "Uma mesma direção.",
    credibilidade: "Credibilidade",
    pesquisa1: "Pesquisa,",
    pesquisa2: "validação e",
    pesquisa3: "registro.",
    credApoio: "Tecnologia aplicada precisa de resultado, rastreabilidade e responsabilidade. Por isso, a BIO-X reúne experiência de campo, validação e registros oficiais.",
    cienciaDia: "Ciência presente no dia a dia",
    altPesquisa: "Pesquisa e validação",
    registrosOficiais: "Registros oficiais",
    vicosa1: "A biotecnologia BIO-X Agricultura Única é citada no material institucional como",
    vicosa2: "aprovada cientificamente pela Universidade Federal de Viçosa",
    altCta: "Possibilidades com a BIO-X",
    umaCiencia: "Uma ciência. Muitas possibilidades.",
    proximo1: "O próximo desafio também pode começar pela",
    proximo2: "biologia.",
    conhecerSolucoes: "Conhecer nossas soluções",
  },
  en: {
    altRaizes: "Plant roots with BIO-X Agricultura Única and with the farm’s standard management, side by side",
    comBiox: "BIO-X Agricultura Única",
    padraoFazenda: "Farm standard",
    ladoALado: "Side by side",
    legendaRaizes: "The same crop, with BIO-X Agricultura Única and with the farm’s standard management.",
    metaTitulo: "About BIO-X",
    metaDescricao: "More than 30 years of experience turned into biotechnology for agriculture, sanitation and animal production.",
    etapas: [["Origin", "Beneficial microorganisms selected to work naturally within biological processes."], ["Application", "The technology is applied directly where the transformation needs to happen."], ["Balance", "The beneficial microorganisms foster a new biological dynamic in the environment."], ["Result", "More balance, efficiency and new possibilities for each production chain."]],
    olhoHero: "The structure behind BIO-X",
    hero1: "Biology that",
    hero2: "spans",
    hero3: "generations.",
    heroApoio: "BIO-X was born from combining more than three decades of experience in agribusiness and wastewater treatment with one of nature’s oldest and most efficient technologies: microorganisms.",
    historiaBotao: "Discover our story",
    cienciaVida: "Science applied to life",
    altDiaCampo: "BIO-X booth at an agribusiness fair",
    expInovacao: "Experience that drives innovation",
    conhecCampo: "Field knowledge turned into technology.",
    historiaCampo: "A story built in the field",
    anos: "+ years",
    expReunindo: "Experience spanning agribusiness, wastewater treatment, research and hands-on application.",
    nossaOrigem: "Our origins",
    antes1: "Before the technology,",
    antes2: "came",
    antes3: "experience.",
    agro: "Agribusiness",
    agroTexto: "Decades in the field built a deep understanding of the real challenges producers face every day.",
    efluentes: "Wastewater treatment",
    efluentesTexto: "Three decades of experience in treatment processes broadened our knowledge of biological balance.",
    pergunta1: "That combination raised a question:",
    pergunta2: "what if biology itself could solve problems that call for complex solutions?",
    altCampo: "Experience in the field",
    altLab: "Technology and laboratory",
    tecBiox: "BIO-X technology",
    processo1: "A natural process.",
    processo2: "A chain reaction of change.",
    processoApoio: "BIO-X technology creates favorable conditions for beneficial microorganisms to play an active role in balancing the environments where they are applied.",
    ilustracao: "Illustration of the stage",
    etapa: "Stage",
    altTextura: "Background texture",
    principio: "The principle",
    natureza1: "Nature doing",
    natureza2: "the heavy lifting.",
    principio1: "Beneficial microorganisms work together with the environment, influencing neutral populations and reducing the conditions that favor unwanted microorganisms.",
    principio2: "The technology is based on microorganisms such as lactobacilli and yeasts, which are also widely known from their use in the food industry.",
    emNumeros: "BIO-X in numbers",
    medida1: "Experience you",
    medida2: "can measure.",
    altResultados: "Results in the field",
    sustenta: "What drives BIO-X",
    principios1: "Three principles.",
    principios2: "One direction.",
    credibilidade: "Credibility",
    pesquisa1: "Research,",
    pesquisa2: "validation and",
    pesquisa3: "registration.",
    credApoio: "Applied technology needs results, traceability and responsibility. That’s why BIO-X brings together field experience, validation and official registrations.",
    cienciaDia: "Science in everyday work",
    altPesquisa: "Research and validation",
    registrosOficiais: "Official registrations",
    vicosa1: "The company’s materials describe the BIO-X Agricultura Única biotechnology as",
    vicosa2: "scientifically approved by the Federal University of Viçosa (Brazil)",
    altCta: "Possibilities with BIO-X",
    umaCiencia: "One science. Many possibilities.",
    proximo1: "Your next challenge can also start with",
    proximo2: "biology.",
    conhecerSolucoes: "Explore our solutions",
  },
  es: {
    altRaizes: "Raíces de plantas con BIO-X Agricultura Única y con el manejo estándar de la finca, lado a lado",
    comBiox: "BIO-X Agricultura Única",
    padraoFazenda: "Estándar de la finca",
    ladoALado: "Lado a lado",
    legendaRaizes: "El mismo cultivo, con BIO-X Agricultura Única y con el manejo estándar de la finca.",
    metaTitulo: "BIO-X",
    metaDescricao: "Más de 30 años de experiencia convertidos en biotecnología aplicada a la agricultura, el saneamiento y la producción animal.",
    etapas: [["Origen", "Microorganismos benéficos seleccionados para actuar de forma natural en los procesos biológicos."], ["Aplicación", "La tecnología se aplica directamente en el ambiente donde debe ocurrir la transformación."], ["Equilibrio", "Los microorganismos benéficos favorecen una nueva dinámica biológica en el medio."], ["Resultado", "Más equilibrio, eficiencia y nuevas posibilidades para cada cadena productiva."]],
    olhoHero: "La estructura detrás de BIO-X",
    hero1: "Biología que",
    hero2: "atraviesa",
    hero3: "generaciones.",
    heroApoio: "BIO-X nació de la unión entre más de tres décadas de experiencia en el agronegocio y en el tratamiento de efluentes con una de las tecnologías más antiguas y eficientes de la naturaleza: los microorganismos.",
    historiaBotao: "Conozca nuestra historia",
    cienciaVida: "Ciencia aplicada a la vida",
    altDiaCampo: "Stand de BIO-X en una feria del agronegocio",
    expInovacao: "Experiencia que genera innovación",
    conhecCampo: "Conocimiento de campo convertido en tecnología.",
    historiaCampo: "Una historia construida en el campo",
    anos: "+ años",
    expReunindo: "Experiencia que reúne agronegocio, tratamiento de efluentes, investigación y aplicación práctica.",
    nossaOrigem: "Nuestro origen",
    antes1: "Antes de la tecnología,",
    antes2: "vino la",
    antes3: "experiencia.",
    agro: "Agronegocio",
    agroTexto: "Décadas de vivencia en el campo construyeron la comprensión de los desafíos reales que enfrentan los productores a diario.",
    efluentes: "Tratamiento de efluentes",
    efluentesTexto: "Tres décadas de experiencia en procesos de tratamiento ampliaron el conocimiento sobre el equilibrio biológico.",
    pergunta1: "De esa combinación surgió una pregunta:",
    pergunta2: "¿y si la propia biología pudiera resolver problemas que exigen soluciones complejas?",
    altCampo: "Experiencia en el campo",
    altLab: "Tecnología y laboratorio",
    tecBiox: "Tecnología BIO-X",
    processo1: "Un proceso natural.",
    processo2: "Una transformación en cadena.",
    processoApoio: "La tecnología BIO-X crea condiciones favorables para que los microorganismos benéficos asuman un papel activo en el equilibrio de los ambientes donde se aplican.",
    ilustracao: "Ilustración de la etapa",
    etapa: "Etapa",
    altTextura: "Textura de fondo",
    principio: "El principio",
    natureza1: "La naturaleza haciendo",
    natureza2: "el trabajo pesado.",
    principio1: "Los microorganismos benéficos actúan en conjunto con el ambiente, influyendo en las poblaciones neutras y reduciendo las condiciones favorables a microorganismos indeseados.",
    principio2: "La base de la tecnología utiliza microorganismos como lactobacilos y levaduras, ampliamente conocidos también por sus aplicaciones en la industria alimentaria.",
    emNumeros: "BIO-X en números",
    medida1: "Experiencia que",
    medida2: "se puede medir.",
    altResultados: "Resultados en el campo",
    sustenta: "Lo que sostiene a BIO-X",
    principios1: "Tres principios.",
    principios2: "Una misma dirección.",
    credibilidade: "Credibilidad",
    pesquisa1: "Investigación,",
    pesquisa2: "validación y",
    pesquisa3: "registro.",
    credApoio: "La tecnología aplicada necesita resultados, trazabilidad y responsabilidad. Por eso, BIO-X reúne experiencia de campo, validación y registros oficiales.",
    cienciaDia: "Ciencia presente en el día a día",
    altPesquisa: "Investigación y validación",
    registrosOficiais: "Registros oficiales",
    vicosa1: "El material institucional cita la biotecnología BIO-X Agricultura Única como",
    vicosa2: "aprobada científicamente por la Universidad Federal de Viçosa (Brasil)",
    altCta: "Posibilidades con BIO-X",
    umaCiencia: "Una ciencia. Muchas posibilidades.",
    proximo1: "El próximo desafío también puede empezar por la",
    proximo2: "biología.",
    conhecerSolucoes: "Conocer nuestras soluciones",
  },
} satisfies Record<Idioma, Record<string, unknown>>;
