import type { Idioma } from "@/i18n/config";

/**
 * Textos da página de clientes nos três idiomas.
 * `setores` segue a ordem de `clientesPorSetor` em src/dados/clientes.ts.
 */
export const textos = {
  pt: {
    olho: "Quem confia na BIO-X",
    h1a: "Gigantes do Brasil",
    h1b: "confiam na nossa biologia.",
    apoio:
      "Concessionárias de saneamento, mineradoras, indústrias de alimentos e grandes construtoras já levaram a tecnologia BIO-X para as suas operações.",
    verClientes: "Ver os clientes",
    serParceiro: "Quero ser parceiro",
    numEmpresas: "empresas na carteira",
    numSetores: "setores atendidos",
    numEstados: "estados com presença",
    numAnos: "anos de experiência",
    letreiroOlho: "Carteira de clientes",
    letreiroTitulo: "Uma mesma tecnologia, do saneamento à indústria.",
    letreiroAria: "Logos dos clientes da BIO-X",
    carteiraOlho: "Por setor",
    carteiraTitulo1: "Conexões que",
    carteiraTitulo2: "atravessam setores.",
    carteiraApoio:
      "Cada setor tem um desafio diferente — e em todos eles a biologia BIO-X já faz parte da operação.",
    empresas: "empresas",
    empresa: "empresa",
    setores: [
      { titulo: "Saneamento e água", texto: "Concessionárias, autarquias e empresas ambientais que tratam água e efluentes em grande escala." },
      { titulo: "Indústria e mineração", texto: "Operações industriais e de mineração, com efluentes complexos e alta exigência ambiental." },
      { titulo: "Alimentos, bebidas e farmacêutica", texto: "Indústrias em que o controle de efluentes e de odores faz parte da rotina de produção." },
      { titulo: "Engenharia e construção", texto: "Construtoras e empresas de engenharia em obras de infraestrutura e saneamento." },
      { titulo: "Outros setores", texto: "Serviços, maquinário e comércio que também contam com a tecnologia BIO-X." },
    ],
    faixaTitulo1: "Confiança construída",
    faixaTitulo2: "na estação, na indústria e no campo.",
    faixaApoio:
      "São mais de três décadas levando biotecnologia para operações que não podem parar.",
    // Programa de parcerias
    parceriaOlho: "Programa de parcerias",
    parceriaH1: "O seu crescimento",
    parceriaH2: "é o nosso crescimento.",
    parceriaApoio:
      "Junte-se à marca que está transformando a biotecnologia a campo. Leve resultados reais para seus clientes e garanta uma nova fonte de rentabilidade para o seu negócio.",
    porque: "Por que a BIO-X?",
    expansao: "Mercado em expansão",
    expansaoTexto: "A biotecnologia agrícola é o setor que mais cresce no agronegócio mundial.",
    retencao: "Retenção de clientes",
    retencaoTexto: "Soluções que entregam resultado geram recompra e fidelização à sua marca.",
    oferecemos1: "Nós oferecemos a biotecnologia.",
    oferecemos2: "Você fortalece sua autoridade.",
    beneficios: [
      ["Rentabilidade e escala", "Modelos comerciais estruturados para garantir margem saudável e crescimento constante do seu negócio junto com a BIO-X."],
      ["Proteção de mercado", "Respeitamos a atuação de cada parceiro. Trabalhamos com políticas claras de região e precificação."],
      ["Tecnologia validada", "Você não vende promessas. Ofereça um portfólio testado, validado por universidades e aprovado por gigantes do mercado."],
      ["Suporte técnico mútuo", "Nossa equipe caminha ao seu lado. Treinamento de ponta para o seu time comercial e suporte direto a campo."],
    ],
    modelosOlho: "Modelos de atuação",
    formato1: "O formato ideal",
    formato2: "para o seu negócio.",
    formatoApoio:
      "Não existe um modelo único. Adaptamos nossa estrutura comercial para atender a realidade e o potencial da sua carteira.",
    perfis: [
      ["Distribuidores e revendas", "Amplie seu portfólio com soluções biotecnológicas de alto valor agregado. Ideal para empresas já estabelecidas na região."],
      ["Cooperativas", "Leve inovação, produtividade e sustentabilidade para os seus cooperados, garantindo a adoção de tecnologias de ponta."],
      ["Consultores agronômicos", "Agregue valor à sua recomendação técnica com soluções que resolvem problemas reais de solo, pragas e produtividade."],
    ],
    jornada: "Inicie sua jornada",
    construir1: "Vamos construir o futuro da",
    construir2: "biotecnologia juntos?",
    whatsappApoio:
      "Envie as informações preliminares pelo WhatsApp. Nosso time de expansão entrará em contato para agendar uma reunião de negócios.",
    falarExpansao: "Falar com a expansão",
    passos: "Próximos passos",
    etapas: [
      ["Alinhamento", "Reunião para entender o seu mercado e o seu potencial comercial."],
      ["Proposta e acordo", "Desenho das margens, região de atuação e assinatura da parceria."],
      ["Treinamento e início", "Capacitação do seu time e ida a campo para as primeiras negociações."],
    ],
    altParceria: "Aperto de mão entre parceiros de negócio",
  },
  en: {
    olho: "Who trusts BIO-X",
    h1a: "Brazil’s industry leaders",
    h1b: "trust our biology.",
    apoio:
      "Sanitation utilities, mining companies, food manufacturers and major construction firms have already brought BIO-X technology into their operations.",
    verClientes: "See our clients",
    serParceiro: "Become a partner",
    numEmpresas: "companies in our client base",
    numSetores: "industries served",
    numEstados: "Brazilian states",
    numAnos: "years of experience",
    letreiroOlho: "Client base",
    letreiroTitulo: "One technology, from sanitation to industry.",
    letreiroAria: "Logos of BIO-X clients",
    carteiraOlho: "By industry",
    carteiraTitulo1: "Connections that",
    carteiraTitulo2: "span industries.",
    carteiraApoio:
      "Every industry has a different challenge — and in all of them, BIO-X biology is already part of the operation.",
    empresas: "companies",
    empresa: "company",
    setores: [
      { titulo: "Sanitation and water", texto: "Utilities, public agencies and environmental companies that treat water and wastewater at scale." },
      { titulo: "Industry and mining", texto: "Industrial and mining operations with complex effluents and strict environmental requirements." },
      { titulo: "Food, beverages and pharma", texto: "Manufacturers for whom effluent and odor control is part of the production routine." },
      { titulo: "Engineering and construction", texto: "Construction and engineering firms working on infrastructure and sanitation projects." },
      { titulo: "Other sectors", texto: "Services, machinery and retail companies that also rely on BIO-X technology." },
    ],
    faixaTitulo1: "Trust built",
    faixaTitulo2: "at the plant, in the factory and in the field.",
    faixaApoio: "More than three decades bringing biotechnology to operations that can’t stop.",
    parceriaOlho: "Partnership program",
    parceriaH1: "Your growth",
    parceriaH2: "is our growth.",
    parceriaApoio:
      "Join the brand that is transforming biotechnology in the field. Bring real results to your clients and secure a new source of revenue for your business.",
    porque: "Why BIO-X?",
    expansao: "A growing market",
    expansaoTexto: "Agricultural biotechnology is the fastest-growing sector in global agribusiness.",
    retencao: "Customer retention",
    retencaoTexto: "Solutions that deliver results drive repeat purchases and loyalty to your brand.",
    oferecemos1: "We provide the biotechnology.",
    oferecemos2: "You strengthen your authority.",
    beneficios: [
      ["Profitability and scale", "Structured commercial models to ensure healthy margins and steady growth for your business alongside BIO-X."],
      ["Market protection", "We respect each partner’s territory. We work with clear regional and pricing policies."],
      ["Validated technology", "You don’t sell promises. Offer a tested portfolio, validated by universities and approved by industry leaders."],
      ["Hands-on technical support", "Our team walks alongside you: top-level training for your sales team and direct support in the field."],
    ],
    modelosOlho: "Partnership models",
    formato1: "The ideal format",
    formato2: "for your business.",
    formatoApoio:
      "There is no one-size-fits-all model. We adapt our commercial structure to the reality and potential of your client base.",
    perfis: [
      ["Distributors and resellers", "Expand your portfolio with high-value biotechnology solutions. Ideal for companies already established in their region."],
      ["Cooperatives", "Bring innovation, productivity and sustainability to your members, ensuring the adoption of cutting-edge technology."],
      ["Agronomy consultants", "Add value to your technical recommendations with solutions that solve real problems of soil, pests and productivity."],
    ],
    jornada: "Start your journey",
    construir1: "Shall we build the future of",
    construir2: "biotechnology together?",
    whatsappApoio:
      "Share some initial information via WhatsApp. Our expansion team will get in touch to schedule a business meeting.",
    falarExpansao: "Talk to our expansion team",
    passos: "Next steps",
    etapas: [
      ["Alignment", "A meeting to understand your market and commercial potential."],
      ["Proposal and agreement", "Defining margins and territory, and signing the partnership."],
      ["Training and launch", "Training your team and heading into the field for the first deals."],
    ],
    altParceria: "Handshake between business partners",
  },
  es: {
    olho: "Quién confía en BIO-X",
    h1a: "Gigantes de Brasil",
    h1b: "confían en nuestra biología.",
    apoio:
      "Concesionarias de saneamiento, mineras, industrias de alimentos y grandes constructoras ya llevaron la tecnología BIO-X a sus operaciones.",
    verClientes: "Ver los clientes",
    serParceiro: "Quiero ser socio",
    numEmpresas: "empresas en la cartera",
    numSetores: "sectores atendidos",
    numEstados: "estados de Brasil",
    numAnos: "años de experiencia",
    letreiroOlho: "Cartera de clientes",
    letreiroTitulo: "Una misma tecnología, del saneamiento a la industria.",
    letreiroAria: "Logos de los clientes de BIO-X",
    carteiraOlho: "Por sector",
    carteiraTitulo1: "Conexiones que",
    carteiraTitulo2: "atraviesan sectores.",
    carteiraApoio:
      "Cada sector tiene un desafío distinto, y en todos ellos la biología BIO-X ya forma parte de la operación.",
    empresas: "empresas",
    empresa: "empresa",
    setores: [
      { titulo: "Saneamiento y agua", texto: "Concesionarias, organismos públicos y empresas ambientales que tratan agua y efluentes a gran escala." },
      { titulo: "Industria y minería", texto: "Operaciones industriales y mineras, con efluentes complejos y alta exigencia ambiental." },
      { titulo: "Alimentos, bebidas y farmacéutica", texto: "Industrias en las que el control de efluentes y olores forma parte de la rutina de producción." },
      { titulo: "Ingeniería y construcción", texto: "Constructoras y empresas de ingeniería en obras de infraestructura y saneamiento." },
      { titulo: "Otros sectores", texto: "Servicios, maquinaria y comercio que también cuentan con la tecnología BIO-X." },
    ],
    faixaTitulo1: "Confianza construida",
    faixaTitulo2: "en la planta, en la industria y en el campo.",
    faixaApoio: "Más de tres décadas llevando biotecnología a operaciones que no pueden parar.",
    parceriaOlho: "Programa de alianzas",
    parceriaH1: "Su crecimiento",
    parceriaH2: "es nuestro crecimiento.",
    parceriaApoio:
      "Únase a la marca que está transformando la biotecnología en el campo. Lleve resultados reales a sus clientes y asegure una nueva fuente de rentabilidad para su negocio.",
    porque: "¿Por qué BIO-X?",
    expansao: "Mercado en expansión",
    expansaoTexto: "La biotecnología agrícola es el sector que más crece en el agronegocio mundial.",
    retencao: "Retención de clientes",
    retencaoTexto: "Las soluciones que entregan resultados generan recompra y fidelización a su marca.",
    oferecemos1: "Nosotros ofrecemos la biotecnología.",
    oferecemos2: "Usted fortalece su autoridad.",
    beneficios: [
      ["Rentabilidad y escala", "Modelos comerciales estructurados para garantizar márgenes saludables y crecimiento constante de su negocio junto a BIO-X."],
      ["Protección de mercado", "Respetamos la actuación de cada socio. Trabajamos con políticas claras de región y precios."],
      ["Tecnología validada", "Usted no vende promesas. Ofrezca un portafolio probado, validado por universidades y aprobado por gigantes del mercado."],
      ["Soporte técnico mutuo", "Nuestro equipo camina a su lado. Capacitación de primer nivel para su equipo comercial y soporte directo en campo."],
    ],
    modelosOlho: "Modelos de actuación",
    formato1: "El formato ideal",
    formato2: "para su negocio.",
    formatoApoio:
      "No existe un modelo único. Adaptamos nuestra estructura comercial a la realidad y el potencial de su cartera.",
    perfis: [
      ["Distribuidores y revendedores", "Amplíe su portafolio con soluciones biotecnológicas de alto valor agregado. Ideal para empresas ya establecidas en la región."],
      ["Cooperativas", "Lleve innovación, productividad y sostenibilidad a sus cooperados, garantizando la adopción de tecnologías de punta."],
      ["Consultores agronómicos", "Agregue valor a su recomendación técnica con soluciones que resuelven problemas reales de suelo, plagas y productividad."],
    ],
    jornada: "Inicie su camino",
    construir1: "¿Construimos juntos el futuro de la",
    construir2: "biotecnología?",
    whatsappApoio:
      "Envíe la información preliminar por WhatsApp. Nuestro equipo de expansión se pondrá en contacto para agendar una reunión de negocios.",
    falarExpansao: "Hablar con expansión",
    passos: "Próximos pasos",
    etapas: [
      ["Alineación", "Reunión para entender su mercado y su potencial comercial."],
      ["Propuesta y acuerdo", "Definición de márgenes, región de actuación y firma de la alianza."],
      ["Capacitación e inicio", "Capacitación de su equipo y salida a campo para las primeras negociaciones."],
    ],
    altParceria: "Apretón de manos entre socios de negocio",
  },
} satisfies Record<Idioma, Record<string, unknown>>;
